### ISSUE TITLE
Document where to place the private ssh key

### ISSUE THREAD

**Issue by berendt** [infraly/k8s-on-openstack#30]
In the REAMDE: "KEY: name of an existing SSH keypair".

But where do you have to place the private ssh key?

**Comment by klippo** [comment]
You should add you private key to openstack

**Comment by klippo** [comment]
Sorry.. I misread. Your ssh-key usually go in ~/.ssh. But it can be placed anywhere and be specified using `ssh -i your_key`. before this works you need to upload your public key in openstack.

**Comment by ctrlaltdel** [comment]
Yes, initial SSH key creation and upload to OpenStack is not really in the scope of these playbooks for now. Here's an example form the CI configuration on how to do it: https://github.com/infraly/k8s-on-openstack/blob/master/.travis.yml#L20.

**Comment by ivveh** [comment]
You could put your private key anywhere and define it in ~/.ssh/config.
IdentifyFile /path/to/private/key
